#!/usr/bin/env bash

# This script injects the 1password secrets from a file to a destination, using the provided token.
# Arguments are passed in the following order:
# 1. The token to authenticate with 1password

sed "s/INSERT_TOKEN_HERE/$1/" ./syncs/secrets/secrets.toml.tpl > ./syncs/secrets/secrets.toml
cat .env.tpl | docker run -i -e OP_SERVICE_ACCOUNT_TOKEN=$1 1password/op op inject > .env
